# Generated by Django 4.2.8 on 2024-05-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, verbose_name='Código do Produto')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_measurement', models.CharField(choices=[('unit', 'Unidades'), ('kilo', 'Quilos'), ('liter', 'Litros')], max_length=20)),
            ],
        ),
    ]
